### ISSUE TITLE
CpuDevice no longer in jax

### ISSUE THREAD

**Issue by adamgayoso** [deepmind/chex#156]
Hello,

Seems like the newest version of jax (0.3.7) removed some classes that are used [here](https://github.com/deepmind/chex/blob/e080c85e93a20df23c23a8ea294cc3e66604efcf/chex/_src/pytypes.py#L40) in chex. Should chex upper bound the jax version? I see this conflicting code is not currently on the main branch -- alternatively, maybe a new release can be made?

https://github.com/google/jax/pull/10326

**Comment by tomhennigan** [comment]
We fixed this in chex in deepmind/chex@7552dfc so yes we would need a new release if a new release of JAX has been made (cc @hbq1 ).

**Comment by adamgayoso** [comment]
Indeed 0.3.7 jax is out now https://pypi.org/project/jax/#history

Thanks!

**Comment by VolodyaCO** [comment]
So, when is this going to be released? @tomhennigan thanks!
