### ISSUE TITLE
Using variants with pytest

### ISSUE THREAD

**Issue by pablo2909** [deepmind/chex#163]
Hi,

First of all thank you for this very useful library !

I have a project in Jax in which I already implemented my tests using pytest. However the possibility that `chex.variants` offers are too nice to ignore. Simultaneously I would like not to rewrite all my test. 

Is there a way to reconcile pytest and chex ? 

Thank you again for all the work!
Best,

**Comment by hbq1** [comment]
Hi, thanks for the kind words!

chex.variants should be compatible with pytest out of the box; have you encountered any issues with it?

**Comment by pablo2909** [comment]
Thank you for getting back to me, it actually works! I ended up writing:

```
from absl.testing import parameterized
class ExampleParameterizedTest(parameterized.TestCase):

  @chex.variants(with_jit=True, without_jit=True)
  @parameterized.named_parameters(
      ('case_positive', 1, 2, 3),
      ('case_negative', -1, -2, -3),
  )
  def test(self, arg_1, arg_2, expected):
    @self.variant
    def var_fn(x, y):
       return x + y

    self.assertEqual(var_fn(arg_1, arg_2), expected)
```
in my test file and `pytest` was able to run it. I guess I was looking for something more convoluted and didn't think of trying the obvious thing to do.  My bad for opening this issue ! I'll close it then :) 

Best
