### ISSUE TITLE
`isinstance(None, (int, float, chex.Array))` raises error since `chex==0.1.7`

### ISSUE THREAD

**Issue by vwxyzjn** [deepmind/chex#261]
Hello,

Thanks for the useful package. I am hitting an error when using the latest chex. See reproduction instructions below.

```
pip install chex==0.1.5 && python -c "import chex; print(isinstance(None, (int, float, chex.Array)))"
```
```
False
```

```
pip install chex==0.1.7 && python -c "import chex; print(isinstance(None, (int, float, chex.Array)))"
```
```
raceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/typing.py", line 769, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/usr/lib/python3.8/typing.py", line 777, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```

This causes an error for optax when trying to use `inject_hyperparams`, which essentially uses `import chex; print(isinstance(None, (int, float, chex.Array)))`

https://github.com/deepmind/optax/blob/04768d252911d6af4d4d36361930ccd0a54f9160/optax/_src/schedule.py#L589

**Comment by hbq1** [comment]
Hi @vwxyzjn, thanks for raising the issue!

Chex pytypes are supposed to be used for type annotations only, and we're fixing `isinstance` checks in various Jax libraries now (it was fixed for Optax with its latest release). For instance checks, you can use either `np.ndarray` or the recently added `jax.Array`, or both.
