### ISSUE TITLE
conda package dependencies

### ISSUE THREAD

**Issue by Muff2n** [deepmind/chex#270]
Apologies if this is the wrong place to post this.

The problem is that the dependencies for the chex package on conda-forge is incorrect: there is a typo in the jax version required.

`conda search chex==0.1.7 --channel conda-forge --info`

returns

```
chex 0.1.7 pyhd8ed1ab_0
-----------------------
file name   : chex-0.1.7-pyhd8ed1ab_0.conda
name        : chex
version     : 0.1.7
build       : pyhd8ed1ab_0
build number: 0
size        : 70 KB
license     : Apache-2.0
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/chex-0.1.7-pyhd8ed1ab_0.conda
md5         : 7d643a09cac375aab18872f92db3b78c
timestamp   : 2023-03-27 14:01:47 UTC
dependencies: 
  - absl-py >=0.9.0
  - dm-tree >=0.1.5
  - jax >=0.1.55
  - jaxlib >=0.1.37
  - numpy >=1.18.0
  - python >=3.6
  - toolz >=0.9.0
  - typing_extensions >=4.2.0
```

But the jax version should be >=0.4.6

**Comment by hbq1** [comment]
Thanks for flagging this! 
@PhilipVinc could you take a look when you get a chance? (or let me know how to update this)

**Comment by PhilipVinc** [comment]
@hbq1 Can't do it right now..

But it's very simple: just make a PR from a branch updating this file

https://github.com/conda-forge/chex-feedstock/blob/main/recipe/meta.yaml

Also bump [the build number](https://github.com/conda-forge/chex-feedstock/blob/740bdffebd728053187d6888b510336264bf988a/recipe/meta.yaml#L14) to 1.

(We can fix this, but unfortunately Conda is terrible for dependency management besides the most recent version and they refuse to fix this kind of issues.)

**Comment by Muff2n** [comment]
@PhilipVinc would you be able to have a look at the PR please?

**Comment by hbq1** [comment]
Ahh apologies -- this issue has slipped under my radar. 
Thanks a lot @PhilipVinc
