### ISSUE TITLE
Fake contexts by calling .start() not working

### ISSUE THREAD

**Issue by sebamenabar** [deepmind/chex#3]
Hi, I tried using both the latest github version and the latest pypi version but in neither using fake contexts by calling .start() works (it did work as a context manager!).
Here some pictures with my problem for fake_pmap and fake_jit:

![Captura de pantalla 2020-09-28 a la(s) 18 27 11](https://user-images.githubusercontent.com/13748963/94488245-a2b03800-01b8-11eb-81f5-141368c1d2b1.png)
![Captura de pantalla 2020-09-28 a la(s) 18 27 20](https://user-images.githubusercontent.com/13748963/94488247-a479fb80-01b8-11eb-92ce-df22524a5b16.png)

What could be the cause of my problem? Thanks

**Comment by stompchicken** [comment]
Hi there!

Thanks for reporting this, it seems that the start/stop methods are indeed not working in the fake contexts. I'm sorry you ran into this issue and I hope you can get by with using the fakes as context manager for now. I'll look into reinstating this functionality.

**Comment by stompchicken** [comment]
This is fixed with commit https://github.com/deepmind/chex/commit/5a226e6ea4cabc16251482b30ef33d995e2792d8
