### ISSUE TITLE
[REQ] Conda recipe

### ISSUE THREAD

**Issue by PhilipVinc** [deepmind/chex#37]
Hi,
I'm the lead developer of [NetKet](https://github.com/netket/netket), an established machine learning / quantum physics package.

We have recently finished rewriting our core to be based on Jax (and flax), and recently released a beta version.
Since many physicists seem to use anaconda, we would also like to update our conda recipe.
However, since we depend on optax (and therefore on Chex), we would need Chex to have a Conda recipe.

Is that something you'd consider? I am willing to volunteer some work to help you.

I tried creating a recipe starting from your pypi source distribution, but that is problematic because you don't bundle your `requirements.txt` file, which is required to run `setup.py`.
I could create a recipe from the tag tarballs on GitHub, but that sometimes prevent the conda packages from auto-updating the recipe for later releases.

**Comment by hbq1** [comment]
Hi, 
Thanks a lot for using Chex and for your offer to help with a Conda recipe! It'd be great to have one for Chex. (and one for Optax :) ) 

Requirements should be included in Chex 0.0.6 (after #38). Please let me know if anything else is needed for setting up the recipe.

**Comment by PhilipVinc** [comment]
it's done. I'll now open a sister issue on the optax repo
